ARG ELASTIC_VERSION

# https://hub.docker.com/_/elasticsearch/tags
FROM elasticsearch:${ELASTIC_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
